# Generated by Django 3.2.12 on 2023-06-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Objet')),
                ('message', models.TextField(verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du service')),
                ('intro', models.TextField(verbose_name='Introduction')),
                ('description', models.TextField(verbose_name='Description du service')),
                ('icon', models.ImageField(upload_to='Images/services', verbose_name='Icon du service')),
                ('image', models.ImageField(upload_to='Images/services', verbose_name='Image du service')),
            ],
        ),
    ]
