# Generated by Django 3.2.12 on 2023-06-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20230618_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='img_detail_page',
            field=models.ImageField(upload_to='Images/services', verbose_name='Image du service pour la page détail'),
        ),
        migrations.AlterField(
            model_name='services',
            name='img_service_page',
            field=models.ImageField(upload_to='Images/services', verbose_name='Image du service pour la page service'),
        ),
    ]
